dist: trusty
sudo: required

services:
  - docker

language: go

go: 
  - "1.12.x"

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.24.0/bazel-0.24.0-linux-x86_64 && chmod +x bazel-0.24.0-linux-x86_64 && sudo mv bazel-0.24.0-linux-x86_64 /usr/local/bin/bazel
  - |
      declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"
      openssl aes-256-cbc \
         -K $encrypted_42099b4af021_key \
         -iv $encrypted_42099b4af021_iv \
         -in ".travis/github_deploy_key.enc" \
         -out "$SSH_FILE" -d
       chmod 600 "$SSH_FILE" \
         && printf "%s\n" \
              "Host github.com" \
              "  IdentityFile $SSH_FILE" \
              "  LogLevel ERROR" >> ~/.ssh/config

install:
  - export GO111MODULE=on
  - go build -o unbazel-gvisor ./cmd/unbazel-gvisor && sudo mv unbazel-gvisor /usr/local/bin/

script:
  - ./sync.sh
