// automatically generated by stateify.

package inet

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *Interface) beforeSave() {}
func (x *Interface) save(m state.Map) {
	x.beforeSave()
	m.Save("DeviceType", &x.DeviceType)
	m.Save("Flags", &x.Flags)
	m.Save("Name", &x.Name)
	m.Save("Addr", &x.Addr)
}

func (x *Interface) afterLoad() {}
func (x *Interface) load(m state.Map) {
	m.Load("DeviceType", &x.DeviceType)
	m.Load("Flags", &x.Flags)
	m.Load("Name", &x.Name)
	m.Load("Addr", &x.Addr)
}

func (x *InterfaceAddr) beforeSave() {}
func (x *InterfaceAddr) save(m state.Map) {
	x.beforeSave()
	m.Save("Family", &x.Family)
	m.Save("PrefixLen", &x.PrefixLen)
	m.Save("Flags", &x.Flags)
	m.Save("Addr", &x.Addr)
}

func (x *InterfaceAddr) afterLoad() {}
func (x *InterfaceAddr) load(m state.Map) {
	m.Load("Family", &x.Family)
	m.Load("PrefixLen", &x.PrefixLen)
	m.Load("Flags", &x.Flags)
	m.Load("Addr", &x.Addr)
}

func (x *TCPBufferSize) beforeSave() {}
func (x *TCPBufferSize) save(m state.Map) {
	x.beforeSave()
	m.Save("Min", &x.Min)
	m.Save("Default", &x.Default)
	m.Save("Max", &x.Max)
}

func (x *TCPBufferSize) afterLoad() {}
func (x *TCPBufferSize) load(m state.Map) {
	m.Load("Min", &x.Min)
	m.Load("Default", &x.Default)
	m.Load("Max", &x.Max)
}

func init() {
	state.Register("inet.Interface", (*Interface)(nil), state.Fns{Save: (*Interface).save, Load: (*Interface).load})
	state.Register("inet.InterfaceAddr", (*InterfaceAddr)(nil), state.Fns{Save: (*InterfaceAddr).save, Load: (*InterfaceAddr).load})
	state.Register("inet.TCPBufferSize", (*TCPBufferSize)(nil), state.Fns{Save: (*TCPBufferSize).save, Load: (*TCPBufferSize).load})
}
