// automatically generated by stateify.

package seqfile

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *SeqData) beforeSave() {}
func (x *SeqData) save(m state.Map) {
	x.beforeSave()
	m.Save("Buf", &x.Buf)
	m.Save("Handle", &x.Handle)
}

func (x *SeqData) afterLoad() {}
func (x *SeqData) load(m state.Map) {
	m.Load("Buf", &x.Buf)
	m.Load("Handle", &x.Handle)
}

func (x *SeqGenerationCounter) beforeSave() {}
func (x *SeqGenerationCounter) save(m state.Map) {
	x.beforeSave()
	m.Save("generation", &x.generation)
}

func (x *SeqGenerationCounter) afterLoad() {}
func (x *SeqGenerationCounter) load(m state.Map) {
	m.Load("generation", &x.generation)
}

func (x *SeqFile) beforeSave() {}
func (x *SeqFile) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
	m.Save("SeqSource", &x.SeqSource)
	m.Save("source", &x.source)
	m.Save("generation", &x.generation)
	m.Save("lastRead", &x.lastRead)
}

func (x *SeqFile) afterLoad() {}
func (x *SeqFile) load(m state.Map) {
	m.Load("Entry", &x.Entry)
	m.Load("SeqSource", &x.SeqSource)
	m.Load("source", &x.source)
	m.Load("generation", &x.generation)
	m.Load("lastRead", &x.lastRead)
}

func init() {
	state.Register("seqfile.SeqData", (*SeqData)(nil), state.Fns{Save: (*SeqData).save, Load: (*SeqData).load})
	state.Register("seqfile.SeqGenerationCounter", (*SeqGenerationCounter)(nil), state.Fns{Save: (*SeqGenerationCounter).save, Load: (*SeqGenerationCounter).load})
	state.Register("seqfile.SeqFile", (*SeqFile)(nil), state.Fns{Save: (*SeqFile).save, Load: (*SeqFile).load})
}
