// automatically generated by stateify.

package time

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *Time) beforeSave() {}
func (x *Time) save(m state.Map) {
	x.beforeSave()
	m.Save("ns", &x.ns)
}

func (x *Time) afterLoad() {}
func (x *Time) load(m state.Map) {
	m.Load("ns", &x.ns)
}

func (x *WallRateClock) beforeSave() {}
func (x *WallRateClock) save(m state.Map) {
	x.beforeSave()
}

func (x *WallRateClock) afterLoad() {}
func (x *WallRateClock) load(m state.Map) {
}

func (x *NoClockEvents) beforeSave() {}
func (x *NoClockEvents) save(m state.Map) {
	x.beforeSave()
}

func (x *NoClockEvents) afterLoad() {}
func (x *NoClockEvents) load(m state.Map) {
}

func (x *ClockEventsQueue) beforeSave() {}
func (x *ClockEventsQueue) save(m state.Map) {
	x.beforeSave()
	m.Save("Queue", &x.Queue)
}

func (x *ClockEventsQueue) afterLoad() {}
func (x *ClockEventsQueue) load(m state.Map) {
	m.Load("Queue", &x.Queue)
}

func (x *Setting) beforeSave() {}
func (x *Setting) save(m state.Map) {
	x.beforeSave()
	m.Save("Enabled", &x.Enabled)
	m.Save("Next", &x.Next)
	m.Save("Period", &x.Period)
}

func (x *Setting) afterLoad() {}
func (x *Setting) load(m state.Map) {
	m.Load("Enabled", &x.Enabled)
	m.Load("Next", &x.Next)
	m.Load("Period", &x.Period)
}

func (x *Timer) beforeSave() {}
func (x *Timer) save(m state.Map) {
	x.beforeSave()
	m.Save("clock", &x.clock)
	m.Save("listener", &x.listener)
	m.Save("setting", &x.setting)
	m.Save("paused", &x.paused)
}

func (x *Timer) afterLoad() {}
func (x *Timer) load(m state.Map) {
	m.Load("clock", &x.clock)
	m.Load("listener", &x.listener)
	m.Load("setting", &x.setting)
	m.Load("paused", &x.paused)
}

func (x *ChannelNotifier) beforeSave() {}
func (x *ChannelNotifier) save(m state.Map) {
	x.beforeSave()
	m.Save("tchan", &x.tchan)
}

func (x *ChannelNotifier) afterLoad() {}
func (x *ChannelNotifier) load(m state.Map) {
	m.Load("tchan", &x.tchan)
}

func init() {
	state.Register("time.Time", (*Time)(nil), state.Fns{Save: (*Time).save, Load: (*Time).load})
	state.Register("time.WallRateClock", (*WallRateClock)(nil), state.Fns{Save: (*WallRateClock).save, Load: (*WallRateClock).load})
	state.Register("time.NoClockEvents", (*NoClockEvents)(nil), state.Fns{Save: (*NoClockEvents).save, Load: (*NoClockEvents).load})
	state.Register("time.ClockEventsQueue", (*ClockEventsQueue)(nil), state.Fns{Save: (*ClockEventsQueue).save, Load: (*ClockEventsQueue).load})
	state.Register("time.Setting", (*Setting)(nil), state.Fns{Save: (*Setting).save, Load: (*Setting).load})
	state.Register("time.Timer", (*Timer)(nil), state.Fns{Save: (*Timer).save, Load: (*Timer).load})
	state.Register("time.ChannelNotifier", (*ChannelNotifier)(nil), state.Fns{Save: (*ChannelNotifier).save, Load: (*ChannelNotifier).load})
}
