// automatically generated by stateify.

package dev

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *Dev) beforeSave() {}
func (x *Dev) save(m state.Map) {
	x.beforeSave()
	m.Save("Dir", &x.Dir)
}

func (x *Dev) afterLoad() {}
func (x *Dev) load(m state.Map) {
	m.Load("Dir", &x.Dir)
}

func (x *filesystem) beforeSave() {}
func (x *filesystem) save(m state.Map) {
	x.beforeSave()
}

func (x *filesystem) afterLoad() {}
func (x *filesystem) load(m state.Map) {
}

func (x *fullDevice) beforeSave() {}
func (x *fullDevice) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
}

func (x *fullDevice) afterLoad() {}
func (x *fullDevice) load(m state.Map) {
	m.Load("Entry", &x.Entry)
}

func (x *nullDevice) beforeSave() {}
func (x *nullDevice) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
}

func (x *nullDevice) afterLoad() {}
func (x *nullDevice) load(m state.Map) {
	m.Load("Entry", &x.Entry)
}

func (x *zeroDevice) beforeSave() {}
func (x *zeroDevice) save(m state.Map) {
	x.beforeSave()
	m.Save("nullDevice", &x.nullDevice)
}

func (x *zeroDevice) afterLoad() {}
func (x *zeroDevice) load(m state.Map) {
	m.Load("nullDevice", &x.nullDevice)
}

func (x *zeroFileOperations) beforeSave() {}
func (x *zeroFileOperations) save(m state.Map) {
	x.beforeSave()
	m.Save("FileOperations", &x.FileOperations)
}

func (x *zeroFileOperations) afterLoad() {}
func (x *zeroFileOperations) load(m state.Map) {
	m.Load("FileOperations", &x.FileOperations)
}

func (x *randomDevice) beforeSave() {}
func (x *randomDevice) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
}

func (x *randomDevice) afterLoad() {}
func (x *randomDevice) load(m state.Map) {
	m.Load("Entry", &x.Entry)
}

func init() {
	state.Register("dev.Dev", (*Dev)(nil), state.Fns{Save: (*Dev).save, Load: (*Dev).load})
	state.Register("dev.filesystem", (*filesystem)(nil), state.Fns{Save: (*filesystem).save, Load: (*filesystem).load})
	state.Register("dev.fullDevice", (*fullDevice)(nil), state.Fns{Save: (*fullDevice).save, Load: (*fullDevice).load})
	state.Register("dev.nullDevice", (*nullDevice)(nil), state.Fns{Save: (*nullDevice).save, Load: (*nullDevice).load})
	state.Register("dev.zeroDevice", (*zeroDevice)(nil), state.Fns{Save: (*zeroDevice).save, Load: (*zeroDevice).load})
	state.Register("dev.zeroFileOperations", (*zeroFileOperations)(nil), state.Fns{Save: (*zeroFileOperations).save, Load: (*zeroFileOperations).load})
	state.Register("dev.randomDevice", (*randomDevice)(nil), state.Fns{Save: (*randomDevice).save, Load: (*randomDevice).load})
}
