// automatically generated by stateify.

package binder

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *Device) beforeSave() {}
func (x *Device) save(m state.Map) {
	x.beforeSave()
	m.Save("InodeNoExtendedAttributes", &x.InodeNoExtendedAttributes)
	m.Save("InodeNotDirectory", &x.InodeNotDirectory)
	m.Save("InodeNotRenameable", &x.InodeNotRenameable)
	m.Save("InodeNotSocket", &x.InodeNotSocket)
	m.Save("InodeNotSymlink", &x.InodeNotSymlink)
	m.Save("NoMappable", &x.NoMappable)
	m.Save("NoopWriteOut", &x.NoopWriteOut)
	m.Save("DeprecatedFileOperations", &x.DeprecatedFileOperations)
	m.Save("unstable", &x.unstable)
}

func (x *Device) afterLoad() {}
func (x *Device) load(m state.Map) {
	m.Load("InodeNoExtendedAttributes", &x.InodeNoExtendedAttributes)
	m.Load("InodeNotDirectory", &x.InodeNotDirectory)
	m.Load("InodeNotRenameable", &x.InodeNotRenameable)
	m.Load("InodeNotSocket", &x.InodeNotSocket)
	m.Load("InodeNotSymlink", &x.InodeNotSymlink)
	m.Load("NoMappable", &x.NoMappable)
	m.Load("NoopWriteOut", &x.NoopWriteOut)
	m.Load("DeprecatedFileOperations", &x.DeprecatedFileOperations)
	m.Load("unstable", &x.unstable)
}

func (x *Proc) beforeSave() {}
func (x *Proc) save(m state.Map) {
	x.beforeSave()
	m.Save("NoFsync", &x.NoFsync)
	m.Save("DeprecatedFileOperations", &x.DeprecatedFileOperations)
	m.Save("NotDirReaddir", &x.NotDirReaddir)
	m.Save("bd", &x.bd)
	m.Save("task", &x.task)
	m.Save("platform", &x.platform)
	m.Save("mapped", &x.mapped)
}

func (x *Proc) afterLoad() {}
func (x *Proc) load(m state.Map) {
	m.Load("NoFsync", &x.NoFsync)
	m.Load("DeprecatedFileOperations", &x.DeprecatedFileOperations)
	m.Load("NotDirReaddir", &x.NotDirReaddir)
	m.Load("bd", &x.bd)
	m.Load("task", &x.task)
	m.Load("platform", &x.platform)
	m.Load("mapped", &x.mapped)
}

func init() {
	state.Register("binder.Device", (*Device)(nil), state.Fns{Save: (*Device).save, Load: (*Device).load})
	state.Register("binder.Proc", (*Proc)(nil), state.Fns{Save: (*Proc).save, Load: (*Proc).load})
}
