// automatically generated by stateify.

package abi

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *OS) save(m state.Map) {
	m.SaveValue("", (int)(*x))
}

func (x *OS) load(m state.Map) {
	m.LoadValue("", new(int), func(y interface{}) { *x = (OS)(y.(int)) })
}

func init() {
	state.Register("abi.OS", (*OS)(nil), state.Fns{Save: (*OS).save, Load: (*OS).load})
}
