// automatically generated by stateify.

package socket

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *ReceiveTimeout) beforeSave() {}
func (x *ReceiveTimeout) save(m state.Map) {
	x.beforeSave()
	m.Save("ns", &x.ns)
}

func (x *ReceiveTimeout) afterLoad() {}
func (x *ReceiveTimeout) load(m state.Map) {
	m.Load("ns", &x.ns)
}

func init() {
	state.Register("socket.ReceiveTimeout", (*ReceiveTimeout)(nil), state.Fns{Save: (*ReceiveTimeout).save, Load: (*ReceiveTimeout).load})
}
