// automatically generated by stateify.

package eventfd

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *EventOperations) beforeSave() {}
func (x *EventOperations) save(m state.Map) {
	x.beforeSave()
	m.Save("val", &x.val)
	m.Save("semMode", &x.semMode)
}

func (x *EventOperations) afterLoad() {}
func (x *EventOperations) load(m state.Map) {
	m.Load("val", &x.val)
	m.Load("semMode", &x.semMode)
}

func init() {
	state.Register("eventfd.EventOperations", (*EventOperations)(nil), state.Fns{Save: (*EventOperations).save, Load: (*EventOperations).load})
}
