// automatically generated by stateify.

package waiter

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *Queue) beforeSave() {}
func (x *Queue) save(m state.Map) {
	x.beforeSave()
	if !state.IsZeroValue(x.list) { m.Failf("list is %v, expected zero", x.list) }
}

func (x *Queue) afterLoad() {}
func (x *Queue) load(m state.Map) {
}

func init() {
	state.Register("waiter.Queue", (*Queue)(nil), state.Fns{Save: (*Queue).save, Load: (*Queue).load})
}
