// automatically generated by stateify.

package ramfs

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *Dir) beforeSave() {}
func (x *Dir) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
	m.Save("children", &x.children)
	m.Save("dentryMap", &x.dentryMap)
}

func (x *Dir) afterLoad() {}
func (x *Dir) load(m state.Map) {
	m.Load("Entry", &x.Entry)
	m.Load("children", &x.children)
	m.Load("dentryMap", &x.dentryMap)
}

func (x *File) beforeSave() {}
func (x *File) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
	m.Save("data", &x.data)
}

func (x *File) afterLoad() {}
func (x *File) load(m state.Map) {
	m.Load("Entry", &x.Entry)
	m.Load("data", &x.data)
}

func (x *Entry) beforeSave() {}
func (x *Entry) save(m state.Map) {
	x.beforeSave()
	m.Save("unstable", &x.unstable)
	m.Save("xattrs", &x.xattrs)
}

func (x *Entry) afterLoad() {}
func (x *Entry) load(m state.Map) {
	m.Load("unstable", &x.unstable)
	m.Load("xattrs", &x.xattrs)
}

func (x *Socket) beforeSave() {}
func (x *Socket) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
	m.Save("ep", &x.ep)
}

func (x *Socket) afterLoad() {}
func (x *Socket) load(m state.Map) {
	m.Load("Entry", &x.Entry)
	m.Load("ep", &x.ep)
}

func (x *Symlink) beforeSave() {}
func (x *Symlink) save(m state.Map) {
	x.beforeSave()
	m.Save("Entry", &x.Entry)
	m.Save("Target", &x.Target)
}

func (x *Symlink) afterLoad() {}
func (x *Symlink) load(m state.Map) {
	m.Load("Entry", &x.Entry)
	m.Load("Target", &x.Target)
}

func init() {
	state.Register("ramfs.Dir", (*Dir)(nil), state.Fns{Save: (*Dir).save, Load: (*Dir).load})
	state.Register("ramfs.File", (*File)(nil), state.Fns{Save: (*File).save, Load: (*File).load})
	state.Register("ramfs.Entry", (*Entry)(nil), state.Fns{Save: (*Entry).save, Load: (*Entry).load})
	state.Register("ramfs.Socket", (*Socket)(nil), state.Fns{Save: (*Socket).save, Load: (*Socket).load})
	state.Register("ramfs.Symlink", (*Symlink)(nil), state.Fns{Save: (*Symlink).save, Load: (*Symlink).load})
}
