// automatically generated by stateify.

package sys

import (
	"gvisor.googlesource.com/gvisor/pkg/state"
)

func (x *filesystem) beforeSave() {}
func (x *filesystem) save(m state.Map) {
	x.beforeSave()
}

func (x *filesystem) afterLoad() {}
func (x *filesystem) load(m state.Map) {
}

func (x *Dir) beforeSave() {}
func (x *Dir) save(m state.Map) {
	x.beforeSave()
	m.Save("Dir", &x.Dir)
}

func (x *Dir) afterLoad() {}
func (x *Dir) load(m state.Map) {
	m.Load("Dir", &x.Dir)
}

func init() {
	state.Register("sys.filesystem", (*filesystem)(nil), state.Fns{Save: (*filesystem).save, Load: (*filesystem).load})
	state.Register("sys.Dir", (*Dir)(nil), state.Fns{Save: (*Dir).save, Load: (*Dir).load})
}
